config: conf/tuning/train_asr_conformer_ctc.yaml
print_config: false
log_level: INFO
drop_last_iter: false
dry_run: false
iterator_type: sequence
valid_iterator_type: null
output_dir: exp/asr_stats_raw_char/logdir/stats.23
ngpu: 0
seed: 0
num_workers: 1
num_att_plot: 3
dist_backend: nccl
dist_init_method: env://
dist_world_size: null
dist_rank: null
local_rank: null
dist_master_addr: null
dist_master_port: null
dist_launcher: null
multiprocessing_distributed: false
unused_parameters: false
sharded_ddp: false
use_deepspeed: false
deepspeed_config: null
gradient_as_bucket_view: true
ddp_comm_hook: null
cudnn_enabled: true
cudnn_benchmark: false
cudnn_deterministic: true
use_tf32: false
collect_stats: true
write_collected_feats: false
max_epoch: 15
patience: 5
val_scheduler_criterion:
- valid
- loss
early_stopping_criterion:
- valid
- loss
- min
best_model_criterion:
-   - train
    - loss
    - min
-   - valid
    - loss
    - min
-   - train
    - acc
    - max
-   - valid
    - acc
    - max
keep_nbest_models:
- 10
nbest_averaging_interval: 0
grad_clip: 5.0
grad_clip_type: 2.0
grad_noise: false
accum_grad: 2
no_forward_run: false
resume: false
train_dtype: float32
use_amp: false
log_interval: null
use_matplotlib: true
use_tensorboard: true
create_graph_in_tensorboard: false
use_wandb: false
wandb_project: null
wandb_id: null
wandb_entity: null
wandb_name: null
wandb_model_log_interval: -1
wandb_allow_val_change: true
detect_anomaly: false
use_adapter: false
adapter: lora
save_strategy: all
adapter_conf: {}
pretrain_path: null
init_param: []
ignore_init_mismatch: false
freeze_param: []
num_iters_per_epoch: null
batch_size: 20
valid_batch_size: null
batch_bins: 8000000
valid_batch_bins: null
category_sample_size: 10
upsampling_factor: 0.5
category_upsampling_factor: 0.5
dataset_upsampling_factor: 0.5
dataset_scaling_factor: 1.2
max_batch_size: null
min_batch_size: 1
train_shape_file:
- exp/asr_stats_raw_char/logdir/train.23.scp
valid_shape_file:
- exp/asr_stats_raw_char/logdir/valid.23.scp
batch_type: numel
valid_batch_type: null
fold_length: []
sort_in_batch: descending
shuffle_within_batch: false
sort_batch: descending
multiple_iterator: false
chunk_length: 500
chunk_shift_ratio: 0.5
num_cache_chunks: 1024
chunk_excluded_key_prefixes: []
chunk_default_fs: null
chunk_max_abs_length: null
chunk_discard_short_samples: true
train_data_path_and_name_and_type:
-   - dump/raw/train/wav.scp
    - speech
    - sound
-   - dump/raw/train/text
    - text
    - text
valid_data_path_and_name_and_type:
-   - dump/raw/dev/wav.scp
    - speech
    - sound
-   - dump/raw/dev/text
    - text
    - text
multi_task_dataset: false
allow_variable_data_keys: false
max_cache_size: 0.0
max_cache_fd: 32
allow_multi_rates: false
valid_max_cache_size: null
exclude_weight_decay: false
exclude_weight_decay_conf: {}
optim: adamw
optim_conf:
    lr: 0.001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000
token_list:
- <blank>
- <unk>
- <space>
- 이
- 그
- 는
- 고
- 가
- 아
- 어
- 하
- 지
- 거
- 에
- 서
- 도
- 다
- 나
- 게
- 을
- 데
- 은
- 있
- 기
- 면
- 니
- 들
- 해
- 라
- 제
- 리
- 로
- 사
- 같
- 까
- 한
- 보
- 를
- 런
- 요
- 래
- 생
- 뭐
- 으
- 인
- 시
- 야
- 만
- 때
- 되
- 자
- 우
- 내
- 많
- 수
- 근
- 대
- 렇
- 더
- 좀
- 안
- 각
- 좋
- 러
- 것
- 일
- 무
- 었
- 스
- 주
- 너
- 정
- 든
- 마
- 간
- 금
- 의
- 구
- 했
- 음
- 부
- 오
- 잖
- 전
- 람
- 말
- 없
- 장
- 진
- 적
- 저
- 할
- 히
- 또
- 여
- 않
- 먹
- 상
- 던
- '1'
- 번
- 려
- 동
- 건
- 비
- 중
- 원
- 냥
- 잘
- 분
- 겠
- 약
- 걸
- 학
- 막
- 랑
- 네
- 문
- 경
- 실
- 식
- 모
- 트
- 친
- 싶
- 드
- '0'
- 짜
- 단
- 맞
- 직
- 집
- 교
- 르
- 물
- 예
- 계
- 신
- 유
- 소
- 운
- 선
- 화
- 바
- 알
- 공
- 긴
- 애
- 조
- 치
- 연
- '2'
- 못
- 봤
- 미
- 타
- 즘
- 성
- 엄
- 행
- 살
- 편
- 노
- 느
- 았
- 얘
- 테
- 재
- 날
- 버
- 처
- 차
- 관
- 용
- 난
- 터
- 본
- 영
- 국
- 럼
- a
- 세
- 개
- 른
- 과
- 키
- 방
- n
- 결
- m
- 점
- 년
- 강
- e
- 갔
- 배
- 와
- 위
- 반
- 업
- 된
- 산
- 속
- 심
- 떤
- 회
- 혼
- 당
- 남
- 피
- 청
- 냐
- 티
- 프
- 명
- 통
- 양
- 입
- 응
- 왜
- 떻
- 봐
- 디
- 돼
- '3'
- 체
- 쪽
- 워
- 님
- 빠
- 갈
- 크
- 브
- 쪼
- 받
- 발
- 뭔
- 힘
- 작
- 올
- 울
- 달
- 될
- 감
- 돈
- 맛
- 언
- 새
- 습
- 억
- 매
- 끔
- 격
- 왔
- 외
- 활
- 력
- 따
- 찮
- 파
- 줄
- 괜
- 불
- 혹
- 준
- 쓰
- 별
- 호
- 두
- 추
- 코
- 등
- 돌
- 딱
- 최
- 취
- 누
- 레
- '5'
- 볼
- 필
- 역
- 질
- 확
- 온
- 얼
- 험
- 임
- 참
- 형
- 민
- 됐
- 져
- 밌
- 설
- 카
- 포
- 겨
- 길
- 족
- 갖
- 굉
- 찾
- 랬
- 였
- 책
- 능
- 천
- 옛
- 끼
- '4'
- 초
- 머
- 종
- 몇
- 현
- 변
- 택
- 품
- 목
- 름
- 희
- 싸
- 루
- 술
- 듣
- 특
- 씩
- 놓
- 절
- 항
- 걔
- 향
- 론
- 열
- 놀
- 낌
- 악
- 폰
- 접
- 닌
- 큰
- 월
- 밥
- 죠
- 후
- 몰
- 곳
- 솔
- 밖
- 늘
- 복
- 투
- 락
- 앞
- 태
- 핑
- 철
- 출
- 린
- 합
- 플
- 박
- 법
- 환
- 순
- 엔
- 벌
- 옷
- 렸
- 깐
- 병
- 담
- 손
- 축
- 쇼
- 움
- 황
- 꼭
- 맨
- 색
- 싫
- 꾸
- 군
- 둘
- 료
- 잡
- 떨
- 완
- 케
- 셨
- 써
- 줘
- 란
- 럴
- 끝
- 평
- 졌
- 빨
- 육
- 슨
- 토
- '6'
- 증
- 충
- 귀
- 튜
- 류
- 쁘
- 릴
- 메
- 커
- 표
- 먼
- 침
- 몸
- 급
- 쉽
- 갑
- 럽
- 김
- 넘
- 찍
- 송
- 함
- 쉬
- 켜
- 골
- 록
- 넣
- 패
- 즈
- 눈
- 독
- 났
- 련
- 백
- 씨
- 웠
- 석
- 쨌
- 똑
- 엠
- 큼
- 뉴
- 쳐
- 죽
- 넷
- 휴
- 랜
- 팔
- 창
- 견
- 찬
- 잠
- 페
- 검
- 즐
- 권
- 녀
- 채
- 슷
- 망
- 삼
- 림
- 션
- 판
- 램
- 획
- 튼
- 닐
- 광
- '8'
- 줬
- 글
- 랐
- '7'
- 높
- 셔
- 츠
- 텐
- 숙
- 걱
- 굳
- 허
- 샀
- 궁
- 밀
- 익
- 멀
- 극
- '9'
- 뒤
- 떠
- 틀
- 승
- 혀
- 듯
- x
- 찌
- 베
- 뭘
- 범
- 짝
- 곡
- 옆
- 챙
- 존
- 블
- 콘
- 퍼
- 째
- 슬
- 젊
- 씀
- 핸
- 씬
- 춰
- 읽
- 며
- 풀
- 답
- 효
- 껴
- 훨
- 탄
- 께
- 웃
- 쯤
- 액
- 잔
- 딸
- 빼
- 깔
- 렵
- 북
- 층
- 굴
- 쁜
- 탈
- 겼
- 탕
- 뀌
- 쿠
- 값
- 깨
- 퇴
- 떡
- 싼
- 센
- 칠
- 율
- 앉
- 뛰
- 붙
- 늦
- 녁
- 쓸
- 클
- 욕
- 착
- 낙
- 텔
- 례
- 팀
- 량
- 곤
- 밤
- 낫
- 덜
- 립
- 졸
- 넌
- 릭
- 헬
- 롭
- 뿐
- 딩
- 첫
- 뮤
- 풍
- 흥
- 벽
- 킬
- 녔
- 징
- 팅
- 봉
- 쩔
- 폐
- 탁
- 냈
- 링
- 털
- 컬
- 빵
- 홍
- 득
- 볶
- 널
- 규
- 념
- 농
- 걷
- 땐
- 빌
- 킨
- 겁
- 턴
- 컴
- 닭
- 삶
- 뜨
- 얻
- 암
- 십
- 픈
- 깊
- 꽤
- 낼
- 끊
- 캐
- 죄
- 냉
- 깝
- 섭
- 엘
- 켓
- 믿
- 엑
- 꺼
- 낮
- 짓
- 멋
- 혈
- 짧
- 놔
- 끌
- 꼈
- 밑
- 놨
- 쌓
- 왕
- 촌
- 헤
- 템
- 냄
- 웨
- o
- 뽑
- 맥
- 끄
- 낳
- 홈
- 넓
- 탔
- 싱
- 염
- 척
- 렴
- 측
- 팝
- 섯
- 컨
- 꿈
- 젠
- 슈
- 퓨
- 덕
- 꼬
- 웬
- 팬
- 닝
- 뜻
- 썼
- 폭
- 렌
- 푸
- 압
- 빙
- c
- 논
- 닥
- 률
- p
- y
- 쟁
- 톡
- 쭉
- 춤
- 맡
- 령
- 룹
- 낸
- 흔
- 랄
- 객
- 땅
- 샤
- 꿔
- 엽
- 킹
- 혜
- 쳤
- 콜
- 릉
- 훈
- 슴
- 빈
- 짐
- 칼
- 찰
- 쌀
- 콩
- 딴
- 겪
- 튀
- 쎄
- 겹
- 쩌
- 럭
- 캠
- 랫
- 숨
- 긍
- 팡
- 봇
- 윤
- 웹
- 뻐
- 즌
- 쓴
- 렀
- 잃
- 꽃
- 릿
- 눠
- 랩
- 흐
- 픽
- 밴
- 롯
- 벗
- 뿌
- 롤
- 줌
- 펜
- 균
- 햄
- 협
- 엇
- 옮
- 낀
- 셋
- 흘
- 옥
- 힙
- 맘
- 녹
- X
- 곱
- 낄
- 뷰
- 멜
- 춘
- 힐
- 댄
- 깜
- 랙
- 툰
- 묻
- 갤
- 좌
- 앱
- 땠
- 끗
- 땜
- 웅
- 꿀
- 틴
- 묘
- 낚
- 빛
- 끓
- 몬
- 델
- 납
- 섬
- 좁
- 밍
- 봄
- 폴
- 총
- 괴
- 낭
- 멤
- 칭
- 큐
- 곧
- 앨
- 퀴
- 빡
- 섞
- 홀
- 딜
- 컵
- 앙
- 앤
- 벨
- 잊
- 찜
- 뷔
- 떼
- 챗
- 쌤
- 탑
- 댁
- 칙
- 욱
- 둔
- 닷
- 빅
- 릎
- t
- 폼
- 꽂
- 틱
- 땀
- 밝
- 칸
- 켰
- 젤
- 닿
- 덩
- 뒷
- 닫
- 몽
- 벤
- 셀
- 벼
- 멘
- 컸
- 킥
- r
- 릇
- 깃
- 룸
- 뻔
- 뀐
- 씻
- 첨
- 딘
- 흡
- 흰
- 톤
- 눌
- 뚱
- 맙
- i
- 렁
- 뇨
- 멍
- 즉
- 쾌
- 똥
- 볍
- 롱
- 됩
- 끈
- 묵
- 뚫
- 쥐
- 둥
- 핫
- 팁
- 왠
- 힌
- 싹
- 촬
- 삭
- 엉
- 팠
- 쟤
- 렛
- 뇌
- 흑
- 핏
- 샐
- 핵
- 둬
- 뢰
- 핀
- 뱅
- 짬
- 뽕
- 놈
- 룰
- 팩
- 벅
- 뼈
- 쌍
- 짖
- 뚜
- 펴
- 븐
- 촉
- 융
- 겸
- 댓
- 숍
- 묶
- 휘
- 띄
- 샌
- 샘
- 헌
- 풋
- 쫓
- 꿨
- 닦
- 붕
- 뒀
- 햇
- 톱
- 믹
- 겉
- 꼼
- 숭
- 덥
- 뺏
- 딪
- 잉
- 멈
- 혔
- 깥
- 밭
- 갓
- 땡
- 짤
- 짠
- 뜯
- 꼽
- 굽
- 꾼
- 셉
- 펙
- 얀
- 빔
- 덮
- 맵
- 략
- 덤
- 늙
- 뱀
- 꽉
- 찐
- 콤
- 곽
- f
- 썰
- 닮
- 뭉
- 맹
- 듭
- 뚝
- 듬
- 팟
- 혁
- 탐
- 삐
- 퀄
- 쌈
- 윗
- 젝
- 첩
- 쫙
- 횟
- 뜬
- 덟
- 덴
- 얇
- 쉴
- 춥
- 렉
- 쵸
- 숫
- 윈
- 낯
- 쿄
- 떴
- 밟
- 봅
- 짱
- 껏
- 듀
- 턱
- 깎
- 쁠
- 썩
- 옵
- 둑
- 펀
- 컷
- 옳
- 헷
- 캣
- 밸
- 뽀
- 앵
- 쿨
- 뤄
- 랍
- 붐
- 쪄
- 잤
- 팽
- 캔
- 빗
- 틈
- 훌
- 씹
- 땄
- 펼
- 숲
- 쏟
- 헐
- 쌌
- 겐
- 잇
- 뜰
- 쏘
- 넉
- 빤
- 빚
- 뺐
- 닉
- 룩
- 홉
- 곰
- 돋
- 뀔
- 찔
- 쫌
- 멸
- 쫄
- 긋
- 엊
- 럿
- 뻤
- 꼴
- 잎
- 맑
- 픔
- 쪘
- 뉘
- 찝
- 팍
- 푹
- 쭤
- 샵
- 돗
- 캡
- 셰
- 쁨
- 젖
- 텍
- 궈
- 굿
- 쿵
- 콕
- 껍
- 앗
- 쭈
- 쯧
- 왼
- 슐
- 뱃
- s
- 삿
- 빴
- 찢
- 쩍
- 쇄
- 륭
- 쏠
- 췄
- 칩
- 텀
- d
- 츄
- 굶
- 귤
- l
- 팥
- 뺀
- 녕
- 긁
- 펫
- 흙
- 흠
- 흉
- 쿼
- 곁
- 젓
- 넥
- 푼
- 줍
- 갚
- 캉
- 웰
- 붓
- 갯
- 맺
- 귈
- 탠
- 랭
- 갱
- 렷
- 횡
- 툭
- 솜
- 룬
- 띠
- 옹
- 킷
- 맣
- 펑
- 탓
- 쑥
- 귄
- 짚
- 툼
- 탱
- 깡
- 톰
- 쩡
- 렬
- 윙
- 틸
- 괌
- 솥
- 뜩
- 갇
- 뺄
- 쇠
- 뻑
- 슘
- 벳
- 잣
- 깅
- 뎅
- 텃
- 넬
- 됨
- 뵙
- 엎
- 딨
- 앓
- 닙
- 쓱
- 깻
- 셜
- 얹
- 펐
- 썸
- 엮
- 꺾
- 몫
- 숑
- 얌
- 샴
- h
- 숏
- 찼
- 혐
- 넛
- 챔
- 훅
- 잼
- 섰
- 륙
- 퉁
- 읍
- 씽
- 뭣
- 멧
- 숯
- 륜
- 헛
- 잭
- 훼
- 딥
- 쌩
- 탭
- 룡
- 뻘
- 왓
- 므
- 켄
- 즙
- 뻥
- 괄
- 핌
- 핥
- 얽
- 뭇
- 뺑
- 벚
- 썹
- 춧
- 댔
- 늬
- 쏙
- 굵
- 뱉
- 렐
- 셧
- 갠
- 뎌
- 킴
- 덧
- 쐬
- 댈
- 첼
- 눅
- 뻗
- 퍽
- 츰
- 삽
- 맏
- 깁
- 멕
- 꼰
- 짰
- 낡
- 똘
- 뛸
- 늑
- 륵
- 잦
- 늄
- 냅
- 칫
- 뿔
- 붉
- 룽
- 쩐
- 뜸
- 섹
- 챠
- 숟
- 얕
- 퀘
- 샷
- 둡
- 얄
- 랠
- 걘
- 껌
- 욘
- 텝
- 꾹
- 씌
- 펄
- 쉰
- 찡
- 씁
- 껑
- 훠
- 휠
- 펠
- 훔
- 쫀
- 룻
- 렘
- 콧
- 볕
- 쉐
- 눕
- 돕
- 랗
- 걀
- 갭
- 듦
- 쌰
- 꽁
- 엌
- 닳
- 쾃
- 툴
- 돔
- 컥
- 흩
- b
- 뻣
- 샹
- 눔
- 얗
- 껄
- 빽
- 텅
- 뤘
- 눴
- 휩
- 덱
- 윳
- 및
- 릅
- 챌
- 싣
- 엣
- 섣
- 쥬
- 넨
- 톨
- 롬
- 밈
- 텨
- 깍
- 셈
- 뛴
- 쨍
- 컹
- 둠
- 뗄
- 밋
- 헨
- 옴
- 쉼
- 엥
- 뵈
- 겟
- 찹
- 닛
- 꿍
- 왈
- 퐁
- 쩜
- 짭
- 륨
- 팸
- 칵
- 랴
- 뿜
- 쿤
- 펌
- 촘
- 싯
- 띵
- 텁
- 떳
- 벙
- 큘
- 폈
- 맴
- 쉘
- 퀸
- 촐
- 헝
- 캄
- 팜
- 켤
- 맷
- 핼
- 탤
- 솟
- 뾰
- 늠
- 헥
- 앴
- 튕
- 헉
- 젯
- 쫑
- 쯔
- 삥
- 찻
- 윌
- 삑
- 쎈
- 댕
- 탬
- 짙
- 겔
- 슛
- 뵀
- 캘
- 쾅
- 꿰
- 왁
- 띡
- 켈
- 썬
- 곗
- 뚤
- 쿡
- 슥
- 쳇
- 틋
- 쑤
- 뒹
- 앰
- 됬
- 짼
- 깬
- 쏴
- 끽
- 엿
- 썽
- 깼
- 킵
- 핍
- 얜
- 굔
- 꿉
- 짊
- 뮬
- 췌
- 냇
- 쌔
- 밉
- 껐
- 헹
- 떄
- 휙
- 꾀
- 뭡
- 끙
- 낑
- 곈
- 깽
- 츤
- 뽈
- 궤
- 괘
- 듄
- 웜
- 곶
- 벡
- 윅
- 껜
- 갛
- 숴
- 빕
- 콰
- 줏
- 랏
- 쌉
- 훑
- 꿇
- 홋
- 넴
- 쩝
- 윽
- 옻
- 딛
- 쨋
- 뽐
- 횐
- 퀵
- 깰
- 샬
- 셌
- 꽝
- 슝
- 캥
- 팰
- 쭘
- 잰
- 녜
- 쉑
- 맸
- 꽈
- 넜
- 툽
- 폿
- 잿
- 펍
- 뵐
- 쟀
- 갬
- 쐐
- 몹
- 뵌
- 맬
- 훗
- 켠
- 뼛
- 뗐
- 텼
- 뿍
- 뱁
- 뿅
- 콥
- 옅
- 딕
- 쏜
- 꺽
- 푀
- 덫
- 놉
- 멩
- 섀
- 팻
- 꿋
- 빳
- 딤
- 똔
- 꼿
- 쬐
- 궂
- 튤
- 낵
- 욜
- 냬
- 뺨
- 톳
- 귿
- 캅
- 숱
- 낱
- 룐
- 첸
- 겅
- 댐
- 씸
- 윷
- 휑
- 딧
- 똠
- 튠
- 쨎
- 앳
- 갸
- 걍
- 쭐
- 펭
- 믄
- 둣
- 껀
- 렜
- 귓
- 봬
- 긱
- 촥
- 뗀
- 샜
- 갉
- 좇
- 랖
- 뤼
- 뮌
- 쮸
- 숄
- 뭄
- 웡
- 짹
- 튈
- 튿
- 뎁
- 냔
- 멱
- 댑
- 팎
- 묽
- 햐
- 쫘
- 묭
- 훤
- 늪
- 캇
- 빻
- 찧
- 탯
- 궐
- 옇
- 펩
- 밧
- 뽁
- 룟
- 샅
- 푯
- 뷸
- 멎
- 혓
- 늉
- 띤
- 튬
- 튄
- 낍
- 닢
- 렙
- 푠
- 듈
- 뜀
- 챘
- 쑈
- 폄
- 웍
- 꽹
- 쏭
- 뮨
- 뎠
- 뉜
- 놋
- 옐
- 뻬
- 뉠
- 몄
- 첵
- 쭝
- 퀼
- 젭
- 겜
- 넵
- 촤
- 픕
- 핬
- 롄
- 짢
- 띈
- 쐈
- 좍
- 깠
- 얏
- 옙
- 쟈
- 큽
- 굼
- 휭
- 쉈
- 슉
- 촛
- 탉
- 붑
- 햅
- 걜
- 삘
- 엡
- 잴
- 쫒
- 얍
- 웩
- 읜
- 곪
- 홧
- 껫
- 멓
- 뗑
- 횔
- 궜
- 웁
- 뎐
- 쭙
- 옌
- 샥
- 욤
- 괏
- 끅
- 쿰
- 쐴
- 틔
- 웻
- 쟨
- 굣
- 쨉
- 퉈
- 믈
- 츈
- 잌
- 뇽
- 볐
- 넋
- 깄
- 샛
- 굥
- 텄
- 뱄
- 읊
- 넙
- 귐
- 묫
- 꿩
- 뙤
- 텟
- 뭍
- 뀨
- 냠
- 쩄
- 뺴
- 젬
- 뎃
- 쐰
- 땔
- 됭
- 뚠
- 욥
- 띔
- 혠
- 릏
- 묜
- 폔
- 갰
- 겆
- 칟
- 뼉
- 삠
- 헴
- 쎘
- 뼘
- 엷
- 녘
- 겄
- 줗
- 쏵
- 쥴
- 챈
- 콱
- 눗
- w
- 촙
- 볏
- 캑
- 닻
- k
- 쥘
- 벴
- 뒨
- 쩠
- 땃
- 씰
- 읏
- 괭
- 캬
- 썻
- 헸
- 겋
- 쥔
- 젼
- 잽
- 퉜
- 떵
- 켁
- 띌
- 퓰
- 킁
- 뀜
- 뱌
- 쿳
- 멨
- 삵
- 갹
- 좃
- 츨
- 휜
- 곯
- 쾰
- 죤
- 쨈
- 뒈
- 냘
- 홑
- S
- D
- R
- W
- v
- 칡
- 삔
- 쒀
- 쎌
- 옜
- 쯥
- 떔
- 봘
- 슌
- 쩨
- 쫍
- 떰
- 힛
- 싰
- 뇐
- 믐
- 맟
- 뫼
- 쌨
- 멉
- 죈
- 삣
- 띨
- 횽
- 꺄
- 잫
- 룔
- 뭏
- 꼐
- 퉤
- 앎
- 넸
- 뽄
- 벵
- 삯
- 뫘
- 솎
- 콸
- 벰
- 쭸
- 뗍
- 겡
- 흣
- 뮈
- 셱
- 뭠
- 퓸
- 꽥
- 뿡
- 먀
- 쐤
- 얠
- 숩
- 셍
- 팃
- 굘
- 봔
- 휼
- 땋
- 쿱
- 캤
- 뗏
- 꽐
- ㅎ
- 퇼
- 좔
- 뀝
- 쌘
- 엪
- 쎙
- 줫
- 뻉
- 빝
- 팄
- 뻿
- 픙
- 욧
- 뗴
- 핟
- 뉼
- 퇵
- 썜
- 몆
- 넒
- 뭥
- 읖
- 읔
- 뎆
- 콴
- 긔
- 둉
- 썡
- 삳
- 믓
- 췸
- 짦
- 떫
- 윔
- 쪾
- 뼜
- 됀
- 헀
- 쐼
- 홱
- 먄
- 쌋
- 옼
- 돛
- 틑
- 쑀
- 뺌
- 몃
- 짯
- 팤
- 놂
- 곌
- 쮜
- 렿
- 닜
- 땝
- 촨
- 얾
- 곔
- 퇘
- 녈
- 덞
- 냫
- 넝
- 쓩
- 짲
- 껶
- 쎅
- 왤
- 읠
- 됌
- 잗
- 쫏
- 덨
- 켭
- 꼇
- 훽
- 읕
- 윕
- 젣
- 팹
- 믾
- 툇
- 뇟
- 깉
- 깟
- 뭿
- 떢
- 꽜
- 왹
- 잟
- 겊
- 옾
- 큔
- 쪌
- 힝
- 챕
- 옉
- 깸
- 캭
- 즛
- 읻
- 끍
- 촵
- 쨀
- 궃
- 걧
- 됏
- 돠
- 셴
- 빰
- 쬘
- 핧
- 맻
- 빱
- 묠
- 냑
- 뉸
- 컫
- 찟
- 풂
- 뷜
- 휸
- 뵜
- 솨
- 옘
- 곬
- 쑨
- 섕
- 뫄
- 젱
- 큿
- 곘
- 찛
- 퀭
- 끋
- 쌂
- 퀀
- 썃
- 눙
- 튭
- 멫
- 펵
- 줆
- 셩
- 쉭
- 떙
- 큭
- 렝
- 켔
- 윰
- 늰
- 흿
- 됙
- 딲
- u
- 팼
- 꿎
- 빋
- 땨
- 쇽
- 죙
- 읩
- 덖
- 옭
- 닺
- 읒
- 왱
- 솝
- 얬
- 쩰
- 웟
- 뮐
- 켕
- 댜
- 낏
- 뎀
- 쌕
- 빢
- 왬
- 첬
- 꾕
- 꼍
- 샨
- 좆
- 틉
- 쏩
- 쎼
- 횬
- 햘
- 맽
- 늇
- 뜹
- 펨
- <sos/eos>
init: null
input_size: null
ctc_conf:
    dropout_rate: 0.0
    ctc_type: builtin
    reduce: true
    ignore_nan_grad: null
    zero_infinity: true
    brctc_risk_strategy: exp
    brctc_group_strategy: end
    brctc_risk_factor: 0.0
joint_net_conf: null
use_preprocessor: true
use_lang_prompt: false
use_nlp_prompt: false
token_type: char
bpemodel: null
non_linguistic_symbols: null
cleaner: null
g2p: null
speech_volume_normalize: null
rir_scp: null
rir_apply_prob: 1.0
noise_scp: null
noise_apply_prob: 1.0
noise_db_range: '13_15'
short_noise_thres: 0.5
aux_ctc_tasks: []
frontend: default
frontend_conf:
    fs: 16k
specaug: null
specaug_conf: {}
normalize: utterance_mvn
normalize_conf: {}
model: espnet
model_conf:
    ctc_weight: 1.0
    lsm_weight: 0.0
preencoder: null
preencoder_conf: {}
encoder: conformer
encoder_conf:
    output_size: 192
    attention_heads: 4
    linear_units: 768
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d
    normalize_before: true
    macaron_style: true
    rel_pos_type: latest
    pos_enc_layer_type: rel_pos
    selfattention_layer_type: rel_selfattn
    activation_type: swish
    use_cnn_module: true
    cnn_module_kernel: 15
postencoder: null
postencoder_conf: {}
decoder: null
decoder_conf: {}
preprocessor: default
preprocessor_conf: {}
required:
- output_dir
- token_list
version: '202604'
distributed: false
